### ISSUE TITLE
Run test suite with `--release-channel=stable`

### ISSUE THREAD

**Issue by tmandry** [rust-lang/release-team#11]
This will help us catch failures that occur when the channel is not nightly, like in https://github.com/rust-lang/rust/pull/84950.

We could also run tests for `beta`, but there are diminishing returns there.

**Comment by emilyalbini** [comment]
Opened a PR with the fix at https://github.com/rust-lang/rust/pull/86098.

**Comment by Mark-Simulacrum** [comment]
Closing -- we've done this now.
