### ISSUE TITLE
Point Releases

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/release-team#4]
I've written up a draft of the RFC here:

https://github.com/Mark-Simulacrum/rfcs/blob/point-releases/text/0000-point-releases-on-a-schedule.md

Please leave initial feedback in this issue. Eventually I guess I'll probably publish it for wider review within the community (preRFC and so forth).

**Comment by Centril** [comment]
Some more drawbacks:
- Increased workload for the release team, e.g. with RELEASES.md, the release post, and the releasing itself. The amount of work hours is maybe 5h total?

More alternatives:
- We could leave this more as a guideline within the 2-4 week window, and leave some example-driven cases of when a PR would be reason enough to do a point release (e.g. "soundness hole fix", "stability hole fix").

> Week 3: all stable backport nominations must be approved during compiler team meeting

(Not just compiler team that might want to backport.)

**Comment by Mark-Simulacrum** [comment]
> Increased workload for the release team, e.g. with RELEASES.md, the release post, and the releasing itself. The amount of work hours is maybe 5h total?

The RFC might not be doing enough to say this, but it should just be RELEASES.md. I estimate the added work on the release team side at approximately 1.5 hours spread across multiple days (writing release notes should be relatively quick, as should backporting -- we would not accept backports that don't merge cleanly). The release process itself is mostly a matter of bumping the channel file, making an announcement on internals, and then running a single command on the chosen date.

> We could leave this more as a guideline within the 2-4 week window, and leave some example-driven cases of when a PR would be reason enough to do a point release (e.g. "soundness hole fix", "stability hole fix").

I'm not sure I follow this alternative. This is the status quo alternative, right? i.e., basically not accepting this RFC? (And as such is already listed in the RFC, I believe, but do correct me if I didn't make that clear enough).

---

The compiler team is not the only team that wants to backport, but I think they're the best suited for judging whether a backport should happen or not today. To my knowledge they are the only team with regular meetings that has the placement to judge such backports. They are also, I expect, reasonably able to do so for pretty much all PRs out there that we would want to backport.

**Comment by Centril** [comment]
> The RFC might not be doing enough to say this, but it should just be RELEASES.md.

Hmm; we did have release blog posts for past point releases though, e.g.:
- https://blog.rust-lang.org/2019/05/14/Rust-1.34.2.html
- https://blog.rust-lang.org/2019/04/25/Rust-1.34.1.html
- https://blog.rust-lang.org/2018/12/20/Rust-1.31.1.html
- ...

So this would be a policy change, right?

> I'm not sure I follow this alternative. This is the status quo alternative, right? i.e., basically not accepting this RFC? (And as such is already listed in the RFC, I believe, but do correct me if I didn't make that clear enough).

It's closer to the status quo, but I'm imagining this as "status quo + clearer guidelines around what to do and when to do". Basically, I think we don't have a lot of clarity right now on what would merit a point release, or at least not a shared articulated vision.

> The compiler team is not the only team that wants to backport, but I think they're the best suited for judging whether a backport should happen or not today. To my knowledge they are the only team with regular meetings that has the placement to judge such backports. They are also, I expect, reasonably able to do so for pretty much all PRs out there that we would want to backport.

Fair points.

**Comment by Mark-Simulacrum** [comment]
Yes, the avoidance of a blog post is a policy change and explicitly intended to mitigate the drawback of increased noise for the community. Though the RFC does not explicitly discuss this (it should, I think) I would expect us to issue blog posts for changes that *today* (before this RFC) would warrant a point release -- specifically, those that you've listed in your clearer guidelines suggestion.

I think if we do go with the clearer guidelines, then I would opt to close the RFC and pursue those guidelines without an RFC (just a forge PR, basically).

**Comment by BatmanAoD** [comment]
I think a _brief_ blog post would be warranted only if the point release causes previously-compiling code to no longer compile (e.g. for soundness hole fixes).

I would also like to add something to our standard blog post verbiage to the effect that "a bugfix release, 1.XX.1, will be made available on [date]." That would ensure that these extra releases are not a surprise.

**Comment by emilyalbini** [comment]
There is a drawback that I don't see mentioned in the RFC: if we start making regular point releases, they won't be something exceptional people need to upgrade to ASAP anymore.

That has a *slight* advantage for us: it allows fixing regressions sooner without people noticing that much. When we released [1.26.1](https://blog.rust-lang.org/2018/05/29/Rust-1.26.1.html), [1.26.2](https://blog.rust-lang.org/2018/06/05/Rust-1.26.2.html), [1.27.1](https://blog.rust-lang.org/2018/07/10/Rust-1.27.1.html) and [1.27.2](https://blog.rust-lang.org/2018/07/20/Rust-1.27.2.html) in quick succession to fix match ergonomics people started to criticize us, and rightfully so, because that feature didn't live up to our quality standards when it was stabilized. Having regular point releases would make it slightly harder for people to notice us fixing features post-release.

This is not something I'd like for us to push though: public scrutiny when we screw something up is good and needed, as it allows us to improve our processes and do better next time.

Also I feel like we need to maintain the exceptionality of our point releases. When a feature needs to be unstabilized or there is an unsoundness, we need people to update ASAP to limit problems in the ecosystem (i.e. new crates using the removed features). Currently point releases are a great way to do that, but if we start to make them regular I worry they might become less effective.

**Comment by Mark-Simulacrum** [comment]
Hm, it's an interesting perspective that more frequent point releases decrease the likelihood that folks will update immediately. Do you feel that the point that any "significant" point release would get a blog post would help alleviate that? I imagine that today most people don't follow even our release schedule, rather they see a blog post "new rust release!" and consider updating at that point.

**Comment by emilyalbini** [comment]
Honestly I don't know, but I'd slightly prefer not to risk. At least to me the motivation doesn't seem that much worth the risk.

**Comment by Mark-Simulacrum** [comment]
So then I guess the right question to ask is: do you feel that this RFCs motivation is insufficient, i.e. the lack of clarity and "slow"(er) rollout of bugfixes isn't a significant enough problem to risk the hypothetical that people will update less quickly?

**Comment by XAMPPRocky** [comment]
Thinking on this more, I would prefer if the RFC was instead a fixed time commitment, say 3–4 stable releases. After which we can review if we want to continue. If people want to try it out new releases I'm happy to support that, but I don't think we should have commit to doing it for the foreseeable future without trying it out first.

**Comment by emilyalbini** [comment]
> So then I guess the right question to ask is: do you feel that this RFCs motivation is insufficient, i.e. the lack of clarity and "slow"(er) rollout of bugfixes isn't a significant enough problem to risk the hypothetical that people will update less quickly?

Yeah.

**Comment by Mark-Simulacrum** [comment]
> Thinking on this more, I would prefer if the RFC was instead a fixed time commitment, say 3–4 stable releases. After which we can review if we want to continue. If people want to try it out new releases I'm happy to support that, but I don't think we should have commit to doing it for the foreseeable future without trying it out first.

I think if we choose to pursue a fixed time commitment approach, then I would personally forgo the RFC and just try things out, though maybe not for quite that long.

@pietroalbini Okay. I guess then it's more "correct" in some sense to say that your main problem is insufficient motivation, so other fixes won't actually help, right? i.e., you don't perceive a problem, so fixing it through expenditure of effort isn't worth it.

I can certainly agree that there's not much of a problem, though I would like to remove the concept of stable-nominations in that case -- i.e., say that we will not do point releases except in exceptional circumstances (as has been our policy so far), and that as such we don't want to spend release team and compiler team time on reviewing those backports.

**Comment by XAMPPRocky** [comment]
> I think if we choose to pursue a fixed time commitment approach, then I would personally forgo the RFC and just try things out, though maybe not for quite that long.

I'm also fine with that, though we should at least make a blog/internals post about trying it out.

**Comment by emilyalbini** [comment]
> Okay. I guess then it's more "correct" in some sense to say that your main problem is insufficient motivation, so other fixes won't actually help, right? i.e., you don't perceive a problem, so fixing it through expenditure of effort isn't worth it.

Yeah. To be clear I still perceive it as a problem, but not as a problem important enough to overcome the drawbacks of addressing it.

> I can certainly agree that there's not much of a problem, though I would like to remove the concept of stable-nominations in that case -- i.e., say that we will not do point releases except in exceptional circumstances (as has been our policy so far), and that as such we don't want to spend release team and compiler team time on reviewing those backports.

I think having `stable-nominated` is still worth it, but maybe we can reform it by having the compiler team look at it and approve it only if the release team decides there is an issue worthy of a point release.

At least from the infrastructure side it's still helpful to keep track of PRs we'd need to backport to stable if we ended up making a point release, for example if an external URL died and we switched to our own mirrors.

**Comment by Mark-Simulacrum** [comment]
Sure, yes, that's a good point re:not removing stable-nominated entirely. The suggested process change there seems fine too.

I have increasingly been thinking that I agree with you that there are many downsides here, and perhaps not enough benefits. I'll leave this open for now, but am currently leaning towards not posting it. :)

**Comment by Centril** [comment]
> I think having `stable-nominated` is still worth it, but maybe we can reform it by having the compiler team look at it and approve it only if the release team decides there is an issue worthy of a point release.

That seems like a good time saving measure for the compiler team potentially (though cc @nikomatsakis @pnkfelix). I agree with the sentiment that having us review what falls under "exceptional circumstances" is still a good idea.

**Comment by BatmanAoD** [comment]
Personally, I think it would be worth trying. Even going into a release cycle with the expectation that we will err on the side of doing a point-release might save us some time discussing it during meetings.
