### ISSUE TITLE
Could wg-triage get write access on rust-lang/rust repo?

### ISSUE THREAD

**Issue by JohnTitor** [rust-lang/release-team#5]
Currently, triage access doesn't allow us to edit issues. It means we have to ping someone who has write access or so when we want to edit issues. Personally, I wouldn't like to ping them each time only to edit it.

for example:
- update outdated examples in OP
- put a checkmark
- add backticks for snippet to be displayed correctly

So, could we get write access?

cc @Mark-Simulacrum and @pietroalbini

**Comment by Mark-Simulacrum** [comment]
I would like @pietroalbini's opinion here in particular, but generally lean towards allowing the access even if that's not great. Ideally we'd have triage access be sufficient here but for whatever reason GitHub has decided that they don't want a role that provides just editing of the issue tracker I guess.

**Comment by emilyalbini** [comment]
Yeah, I'd be ok for this since most of the triagers are trusted now.

**Comment by JohnTitor** [comment]
So, I'd say that this request is approved, thanks! Could @Mark-Simulacrum or @pietroalbini give us the access?

**Comment by emilyalbini** [comment]
Updated the permissions.
